version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: chore

  - package-ecosystem: gomod
    directory: /mcp-servers/kubectl-mcp
    schedule:
      interval: weekly
    commit-message:
      prefix: chore

  - package-ecosystem: gomod
    directory: /mcp-servers/flux-mcp
    schedule:
      interval: weekly
    commit-message:
      prefix: chore

  - package-ecosystem: gomod
    directory: /mcp-servers/ssh-mcp
    schedule:
      interval: weekly
    commit-message:
      prefix: chore

  - package-ecosystem: gomod
    directory: /mcp-servers/nixos-mcp
    schedule:
      interval: weekly
    commit-message:
      prefix: chore

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
