apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-backend
  namespace: default
  labels:
    app: app-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-backend
  template:
    metadata:
      labels:
        app: app-backend
    spec:
      containers:
        - name: app-backend
          image: hashicorp/http-echo
          args:
            - "-listen=:80"
            - "-text=ok"
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "16Mi"
            limits:
              memory: "64Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: app-backend
  namespace: default
  labels:
    app: app-backend
spec:
  selector:
    app: app-backend
  ports:
    - port: 80
      targetPort: 80
