apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - app-backend.yaml
  - vigil-app.yaml
  - vigil-app-nginx-config.yaml
  - vigil-app-pullsecret.yaml
  - postgresql
  - redis
