apiVersion: apps/v1
kind: Deployment
metadata:
  name: vigil-app
  namespace: default
  labels:
    app: vigil-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vigil-app
  template:
    metadata:
      labels:
        app: vigil-app
    spec:
      containers:
      - name: vigil-app
        image: nginx:stable
        resources:
          requests:
            memory: 64Mi
          limits:
            memory: 128Mi
        env:
        - name: APP_CRASH_MODE
          value: '0'
