apiVersion: v1
kind: ConfigMap
metadata:
  name: vigil-app-nginx-config
  namespace: default
data:
  default.conf.template: |
    server {
        listen 80;
        location / {
            proxy_pass http://api-backend:8080;
        }
    }