apiVersion: apps/v1
kind: Deployment
metadata:
  name: vigil-app
  namespace: default
spec:
  selector:
    matchLabels:
      app: vigil-app
  template:
    metadata:
      labels:
        app: vigil-app
    spec:
      containers:
      - name: vigil-app
        image: vigil-app:latest