apiVersion: apps/v1
kind: Deployment
metadata:
  name: vigil-app
  namespace: default
  labels:
    app: vigil-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vigil-app
  template:
    metadata:
      labels:
        app: vigil-app
    spec:
      containers:
      - name: vigil-app
        image: nginx:stable
        env:
        - name: REQUIRED_API_BASE
          value: 'http://app-backend.default.svc.cluster.local:80'
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 2
          periodSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: 64Mi
          limits:
            memory: 128Mi
        volumeMounts:
        - name: nginx-config-template
          mountPath: /etc/nginx/templates
          readOnly: true
      - name: mem-load
        image: polinux/stress
        command:
        - stress
        - --vm
        - '1'
        - --vm-bytes
        - 50M
        - --vm-keep
        resources:
          requests:
            memory: 8Mi
          limits:
            memory: 96Mi
      volumes:
      - name: nginx-config-template
        configMap:
          name: vigil-app-nginx-config