apiVersion: v1
kind: Secret
metadata:
  name: vigil-app-pullsecret
  namespace: default
  labels:
    eval-scenario: boundary-1
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5leGFtcGxlLmludmFsaWQiOnsiYXV0aCI6ImRYTmxjanB3WVhOeiJ9fX0=
