apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-infrastructure
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: cluster-sources
    - name: cluster-secrets
  path: ./infra/overlays/hetzner/kubernetes/clusters/hetzner/infrastructure
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: kube-prometheus-stack
      namespace: monitoring
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: longhorn
      namespace: longhorn-system
  timeout: 15m
