apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-secrets
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: cluster-namespaces
  path: ./infra/overlays/hetzner/kubernetes/clusters/hetzner/secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
