apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-sources
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: cluster-namespaces
  path: ./infra/overlays/hetzner/kubernetes/clusters/hetzner/sources
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
