apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vigil-app-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 100Mi
