apiVersion: v1
kind: Secret
metadata:
    name: vigil-webhook-secret
    namespace: monitoring
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:Vn/av/q/GKukihiZY90pcry1hXK91y2r7qQiR+jcpiFFYqHwHhedmM471LU=,iv:hrUQsFlcFwBFIpnlowzPD2nGDQKe8SilIHo8j+EwUzc=,tag:OE3ENxs4Wfu1PiL3L3nshw==,type:str]
sops:
    age:
        - recipient: age1sd72gjj4689pgw6lnzu7kac8dlstxt2elfxgr0urv5nml20569zsrkylka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKOEdDbTNtV2oxbndUVnlZ
            ajlDUkdzMDBTYnZsUUw0RDhKV3lIUkk2RkJZCjlkaWtaYU9qZW1Ca2FkdXcvakE4
            bWEydjg1dmt0elQ4aktPaTJXSklSN0UKLS0tIFMzTmhzcjJ0QzNDb2JqTlZPcFF0
            WUlmc3ZJUXZmWmJ4eFZjdDBjRldyaGMKzQogaC633wgGU0mdjovbIJ9sGY9hDLNr
            rkjovvJl9o5c5dba+RMQhPZILTZAvUgv/7HXXcmyRtnr6Rz5lj4iCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-20T19:09:38Z"
    mac: ENC[AES256_GCM,data:oc9KJUawFykvzMMGWR8I51ZyMthk9QkoSTKH8lTDC/4B3u/DPMlAnPhGgeJDmJFk9dqvVqJjw723kl0LW1hVb2yFo2xWbgVgQBfLNjFBBOKOWAZVdUWqT3iu05/60E693x5zdc6FP1+K3Q9AdchAxkX0M6sfgC0BMEikVvnWAJM=,iv:mZNYPCd7P5BZG28TGnaE7k9R4vV40NIqfPzrSUhe25g=,tag:YtlXQTCFidtwEOFXdxOLng==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
