apiVersion: v1
kind: Secret
metadata:
    name: vigil-webhook-secret
    namespace: monitoring
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:6JSnSBJFHMSRmnZKPDFIPCwRjNSeEJ+yJhdfOJ3D7CO+BZNclwHPcJ8yRGI=,iv:zAC9WEUMSumPdrsehyUOq/PwoOAGMnjjZO+x8+uZBnI=,tag:2hOCah4wzeD6gOCWq0MpXA==,type:str]
sops:
    age:
        - recipient: age1sd72gjj4689pgw6lnzu7kac8dlstxt2elfxgr0urv5nml20569zsrkylka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dXpKaWVFUHY4c2MrU25T
            TUl4K2puZTV6WmpZWUVyMTZaL2QrSkR1a2cwCjN2RSt1QU5XemJVaFk5V2JXeUIw
            U0RQQS9FRyt2dHFSbmJ6ZVVVMzM5SjAKLS0tIFZ2ekhIM3c4cEgxT0dTOWlQL2tn
            eUtCM2VLQ2xIcFJ0TlJaQ2IxRXZGTFUKq+tbVbjtP1LXNNaj5O6eUbDz4RMgXEAd
            cc9okIhuVzhnL1bGsyL0dgeFzKMY6znSRyV5tBpoP1WQ7ghkXpIAuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-20T19:09:09Z"
    mac: ENC[AES256_GCM,data:glGVBFLO5uuqvr0/6VICae1h5jCphdvlceI+eS6hh91NLuPGhuaoGLQwMa/FDqMswV4HgABguscbVe2A/FmkVcOhbgHFsD0cnYmbCyDFsTG09u0Hqf+fJ0o6TXGGr1YKY5tm09FZ5xymO0p11KXEOfs2pcnZIWfxJBiGcTLEg6I=,iv:BOFsgVad69KJLvmQ2dY5vUGMjNuobiaDANMh/Y00dKU=,tag:yZqYYXZdCv4LRR1/03wdfw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
